# Workflow for deploying static content to GitHub Pages

name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: yarn && yarn build

      - name: Domain
        run: echo -n lotofacil.gn.dev.br > build/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
