name: Run Script

on:
  push:
    branches: [ master ]

jobs:

  generate:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        parts: [
          todos.part1.txt 1 100,
          todos.part2.txt 101 200,
          todos.part3.txt 201 300,
          todos.part4.txt 301 400
        ]

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: 'yarn'

      - name: Install Modules
        run: yarn

      - name: Run Script
        run: yarn generate ${{ matrix.parts }}

      - name: Commit
        run: |
          git config --global user.email "guilhermeasn@yahoo.com.br"
          git config --global user.name "Guilherme Neves"
          git pull
          git add .
          git commit -am '${{ matrix.parts }}'
          git push --force
